### ISSUE TITLE
Works incorrectly

### ISSUE THREAD

**Issue by kvolkovich-sc** [dotemacs/ipcalc.el#7] opened 2017-06-28 08:38 UTC
Hi!

Package installed from MELPA. Version 20160927.220

Input: 

```
192.168.7.94/24
```

Output:

```
Address:  "192.168.7.94         00000000101010000000011101011110
Netmask:   255.255.255.0 = 24"   11111111111111111111111100000000
Wildcard:  0.0.0.255            00000000000000000000000011111111
=>
Network:     0.168.7.0          00000000101010000000011100000000
HostMin:     0.168.7.1          00000000101010000000011100000001
HostMax:     0.168.7.254        00000000101010000000011111111110
Broadcast:   0.168.7.255        00000000101010000000011111111111
Hosts/Net: 254
```

Network, HostMin, HostMax, Broadcast have wrong values.

**Comment by dotemacs** [comment] 2017-06-28 08:53
Hello @kvolkovich-sc 

how did you invoke `ipcalc`?

I did <kbd>M-x</kbd> `ipcalc` <kbd>RET</kbd>. At the prompt: `IP/CIDR:` I entered `192.168.7.94/24` <kbd>RET</kbd> and the output is:

```
Address:   192.168.7.94         11000000101010000000011101011110
Netmask:   255.255.255.0 = 24   11111111111111111111111100000000
Wildcard:  0.0.0.255            00000000000000000000000011111111
=>
Network:   192.168.7.0          11000000101010000000011100000000
HostMin:   192.168.7.1          11000000101010000000011100000001
HostMax:   192.168.7.254        11000000101010000000011111111110
Broadcast: 192.168.7.255        11000000101010000000011111111111
Hosts/Net: 254
```

In my `*scratch*` buffer I entered:

```emacs-lisp
(ipcalc "192.168.7.94/24")
```
and evaluated that expression, which produced the same output as I've included above.

How are you  using it?

**Comment by dotemacs** [comment] 2017-06-28 08:56
And I'm also using `ipcalc-20160927.220`, from MELPA.

**Comment by kvolkovich-sc** [comment] 2017-06-28 09:04
I found the mistake.
If <kbd>M-x</kbd> ipcalc <kbd>RET</kbd> => `192.168.7.94/24` - All is OK
If <kbd>M-x</kbd> ipcalc <kbd>RET</kbd> => `"192.168.7.94/24"` (with quotes) - Bug reproduced

Not a huge problem. Maybe you shouldn't fix it)

**Comment by dotemacs** [comment] 2017-06-28 09:11
Aha :)

Thanks for that.

If you want, feel free to do a PR :)

**Comment by kvolkovich-sc** [comment] 2017-06-28 09:13
Ok. On this weekend =)

**Comment by dotemacs** [comment] 2017-06-28 09:17
The issue is here: https://github.com/dotemacs/ipcalc.el/blob/master/ipcalc.el#L148

Just replace all occurrences of quotes. Maybe with `replace-regexp-in-string`? But it's up to you.

Thanks in any case :)

**Comment by dotemacs** [comment] 2020-08-09 14:44
Fixed with https://github.com/dotemacs/ipcalc.el/commit/82a1b9a4a5c822afe7341ca84af7767cbcb8ceea

Thanks @kvolkovich-sc

**Closed by dotemacs** 2020-08-09 14:44 UTC
